const { createCanvas } = require("canvas");

const wrapLines = (context, text, maxWidth, maxLines) => {
    const words = String(text || "").split(/\s+/);
    const lines = [];
    let line = "";
    for (const word of words) {
        const candidate = line ? `${line} ${word}` : word;
        if (context.measureText(candidate).width <= maxWidth) {
            line = candidate;
            continue;
        }
        if (line) lines.push(line);
        line = word;
        if (lines.length === maxLines - 1) break;
    }
    if (line && lines.length < maxLines) lines.push(line);
    return lines;
};

const createDocumentThumbnail = ({ title, documentNumber, revision }) => {
    const canvas = createCanvas(680, 880);
    const context = canvas.getContext("2d");

    context.fillStyle = "#e7ece8";
    context.fillRect(0, 0, canvas.width, canvas.height);
    context.fillStyle = "#365642";
    context.fillRect(0, 0, 18, canvas.height);
    context.fillStyle = "#294132";
    context.font = "700 24px Arial";
    context.fillText("CONTROLLED DOCUMENT", 64, 86);
    context.fillStyle = "#758179";
    context.font = "18px Arial";
    context.fillText(documentNumber || "MES DOCUMENT CENTER", 64, 130);

    context.fillStyle = "#203329";
    context.font = "700 55px Georgia";
    const lines = wrapLines(context, title, 550, 5);
    lines.forEach((line, index) => context.fillText(line, 64, 275 + index * 70));

    context.strokeStyle = "#b6c1b9";
    context.beginPath();
    context.moveTo(64, 742);
    context.lineTo(616, 742);
    context.stroke();
    context.fillStyle = "#607067";
    context.font = "700 18px Arial";
    context.fillText(`REVISION ${revision || 0}`, 64, 792);
    context.font = "16px Arial";
    context.fillText("Generated by MES Document Center", 64, 825);

    return canvas.toBuffer("image/png");
};

module.exports = {
    createDocumentThumbnail,
};
