export const labels = {
    en: {
        title: 'Send to your desktop', connecting: 'Connecting…', connected: 'Phone paired', reconnecting: 'Reconnecting…',
        instructions: 'Select images or files. Your desktop operator accepts and chooses where to save.',
        images: 'Upload image', files: 'Upload file', send: 'Send request', cancel: 'Cancel transfer',
        expiry: 'Expires after 10 minutes without activity, and always within 24 hours. Keep this page open while sending.',
        waiting: 'Waiting for desktop acceptance', sending: 'Sending…', finishing: 'Saving on desktop…', complete: 'Saved on desktop',
        declined: 'Desktop declined the request', cancelled: 'Cancelled', failed: 'Could not transfer directly. Check the connection and send a new request.',
        timeout: 'Transfer timed out. Send a new request.', expired: 'This link has expired. Create a new QR code on your desktop.',
        ended: 'This link has ended. Create a new QR code on your desktop.', unavailable: 'This link is invalid, already used, or expired. Create a new QR code on your desktop.',
        unsupported: 'Use a browser with WebRTC support over HTTPS.', selectionError: 'Choose up to 10,000 files with a valid total size.',
        batch: 'Phone upload', progress: 'Transfer progress', expires: 'Access expires: ',
    },
    cn: {
        title: '发送到电脑', connecting: '正在连接…', connected: '手机已配对', reconnecting: '正在重新连接…',
        instructions: '选择图片或文件。电脑端操作员接受后选择保存位置。', images: '上传图片', files: '上传文件', send: '发送请求', cancel: '取消传输',
        expiry: '无操作或传输进度达10分钟后过期，最长有效24小时。发送时请保持此页面打开。',
        waiting: '等待电脑接受', sending: '正在发送…', finishing: '正在电脑上保存…', complete: '已保存到电脑', declined: '电脑已拒绝请求', cancelled: '已取消',
        failed: '无法直接传输。请检查连接后重新发送请求。', timeout: '传输超时。请重新发送请求。', expired: '链接已过期。请在电脑上创建新的二维码。',
        ended: '链接已终止。请在电脑上创建新的二维码。', unavailable: '链接无效、已使用或已过期。请在电脑上创建新的二维码。',
        unsupported: '请使用支持WebRTC的浏览器并通过HTTPS访问。', selectionError: '请选择最多10,000个文件，且总大小有效。', batch: '手机上传', progress: '传输进度', expires: '访问截止时间：',
    },
    es: {
        title: 'Enviar al escritorio', connecting: 'Conectando…', connected: 'Teléfono vinculado', reconnecting: 'Reconectando…',
        instructions: 'Selecciona imágenes o archivos. El operador del escritorio acepta y elige dónde guardarlos.', images: 'Subir imagen', files: 'Subir archivo', send: 'Enviar solicitud', cancel: 'Cancelar transferencia',
        expiry: 'Caduca tras 10 minutos sin actividad y siempre antes de 24 horas. Mantén esta página abierta durante el envío.',
        waiting: 'Esperando aceptación del escritorio', sending: 'Enviando…', finishing: 'Guardando en el escritorio…', complete: 'Guardado en el escritorio', declined: 'El escritorio rechazó la solicitud', cancelled: 'Cancelado',
        failed: 'No se pudo transferir directamente. Revisa la conexión y envía otra solicitud.', timeout: 'La transferencia agotó el tiempo. Envía otra solicitud.', expired: 'El enlace ha caducado. Crea otro código QR en el escritorio.',
        ended: 'El enlace ha terminado. Crea otro código QR en el escritorio.', unavailable: 'Enlace inválido, usado o caducado. Crea otro código QR en el escritorio.',
        unsupported: 'Usa un navegador compatible con WebRTC mediante HTTPS.', selectionError: 'Elige hasta 10.000 archivos con un tamaño total válido.', batch: 'Carga del teléfono', progress: 'Progreso de transferencia', expires: 'El acceso caduca: ',
    },
    ja: {
        title: 'パソコンに送信', connecting: '接続中…', connected: 'スマートフォンを接続しました', reconnecting: '再接続中…',
        instructions: '画像またはファイルを選択してください。パソコンの操作員が承認して保存先を選択します。', images: '画像をアップロード', files: 'ファイルをアップロード', send: 'リクエストを送信', cancel: '転送をキャンセル',
        expiry: '操作や転送の進行が10分間ない場合、または作成から24時間で期限切れになります。送信中はこのページを開いたままにしてください。',
        waiting: 'パソコンの承認を待っています', sending: '送信中…', finishing: 'パソコンに保存中…', complete: 'パソコンに保存しました', declined: 'パソコンがリクエストを拒否しました', cancelled: 'キャンセルしました',
        failed: '直接転送できませんでした。接続を確認して再送信してください。', timeout: '転送がタイムアウトしました。再送信してください。', expired: 'リンクの有効期限が切れました。パソコンで新しいQRコードを作成してください。',
        ended: 'リンクは終了しました。パソコンで新しいQRコードを作成してください。', unavailable: 'リンクが無効、使用済み、または期限切れです。パソコンで新しいQRコードを作成してください。',
        unsupported: 'HTTPS接続でWebRTC対応ブラウザーを使用してください。', selectionError: '合計サイズが有効なファイルを10,000個以内で選択してください。', batch: 'スマートフォンからのアップロード', progress: '転送の進行状況', expires: 'アクセス有効期限：',
    },
};
